### ISSUE TITLE
User Get avatar does not work

### ISSUE THREAD

**Issue by locohost** [DiscordAPI/docs#6]
No matter what I enter for my own :avatar_id as shown in the doc, I get no avatar. The return result is always { "message": "" }.

This is what I'm trying and what makes sense, but it's wrong...

https://discordapp.com/api/users/d6games/avatars/d6games.jpg

Is ":avatar_id" not my user handle? If not, how can I get a Player's (secret?) "avatar_id" so I can display their Discord avatar in my game?

**Comment by meew0** [comment]
A user's avatar ID will be sent with the user data in the READY packet (or other packets where the user is updated). You would use your own user ID and the avatar ID as the two arguments to the request, respectively.

**Comment by locohost** [comment]
I'm not sure what a "READY" packet is. No Discord url I call returns anything but { "message": "" } Would you mind posting some examples of how I can get the avatar_id?

**Comment by amishshah** [comment]
The READY packet is sent over WebSocket. I'm fairly certain you can only get the avatar_id from packets received over WebSocket, not XHR

**Comment by abalabahaha** [comment]
@locohost are you using one of the unofficial libraries?

**Comment by locohost** [comment]
I'm not sure. I downloaded from Discord site. What I was hoping the api would provide is a simple way to use Discord player avatars in my NWjs game. It looks like we need another REST GET method to pull avatar_id strings prior to calling the method that returns the avatar image.

**Comment by locohost** [comment]
Could the login method return more than just a token? That could include the avatar_id. Or another GET method that we can call (including the login token) to pull simple user public info/stats, including avatar_id.

**Comment by abalabahaha** [comment]
https://discordapi.readthedocs.org/en/latest/reference/guilds/members.html ?

**Comment by locohost** [comment]
Yes I saw that. But that means the Player must be member of a "Guild" on Discord and then they must tell me the guild before I can look them up. What if they're not in a guild? This is not what we need. We need a simple REST GET to easily pull any Player's public stats with just their Player handle and/or a login token.

**Comment by locohost** [comment]
I suppose I can create a guild named "MyGameName". Then create some channels in that guild like "Beginner", "Advanced", etc. Then when the game starts, get their Player handle, look for them in the default guild, if they're not there, tell them the must open Discord and join that guild. I don't see a way in the api to join a Player to a guild. Am I missing that?

Does this seem like the right way?

**Comment by meew0** [comment]
I think you don't realize that this API is made for Discord's internal use. Any design decisions were made for good integration with Discord's default client. The people in here just reverse engineered the protocol and put up some docs for it.

As for your question: unless you have a bot running on a server (= guild) that also has the people in it you want to get the avatar from, there's no way to do it. If you have that, great, I suggest using one of the [unofficial libraries](https://abal.moe/Discord/Libraries.html) to do your task. If not, it would probably be easier to make your users submit their avatars manually.

**Comment by locohost** [comment]
Hmm interesting. When I asked on Twitter about a Discord public API to be used for integrating our games, the response was "Coming soon!". So this _is not_ that public API?

**Comment by meew0** [comment]
No, this is just Discord's internal API, reverse-engineered. A public API has been confirmed by the devs, but there's no ETA and barely any other information about it.

**Comment by locohost** [comment]
Damn, I apologize. I close this.
