### ISSUE TITLE
Websocket keepalive

### ISSUE THREAD

**Issue by gdude2002** [DiscordAPI/docs#8]
The docs [aren't really clear](https://github.com/DiscordAPI/docs/blob/master/docs/reference/websockets/general.rst#message-via-websocket-1) on this - Do we simply send an empy message, or is there some missing payload here?

**Comment by abalabahaha** [comment]
I haven't dealt with websockets, but judging from a few libraries' code, I'm going to guess the payload is

```
{
    "op":1,
    "d": timestamp (milliseconds since Jan 1 1970)
}
```

**Comment by gdude2002** [comment]
Thanks, I'll give that a shot.

**Comment by gdude2002** [comment]
Yep, that's the one. Thanks. I guess they must be using socket.io or something like that.
